function nowIso() {
  return new Date().toISOString();
}

export function plannerAgent({ objective, constraints = {} }) {
  return {
    created_at: nowIso(),
    objective,
    constraints,
    task_graph: {
      tasks: [
        {
          id: 'T1',
          title: 'Scaffold landing page',
          description: 'Create index.html + basic styling + README',
          type: 'frontend',
          dependencies: [],
          acceptance: ['index.html exists', 'README contains objective'],
          files_touched: ['index.html', 'README.md'],
          ci_required: true,
        },
        {
          id: 'T2',
          title: 'Add CI workflow',
          description: 'Add CI workflow that validates required files',
          type: 'test',
          dependencies: ['T1'],
          acceptance: ['CI runs on PR', 'CI fails if index.html missing'],
          files_touched: ['.github/workflows/ci.yml'],
          ci_required: true,
        },
      ],
    },
  };
}

export function coderAgent({ objective, task }) {
  const branch = `feature/${String(task?.id || 'task').toLowerCase()}`;

  if (task?.id === 'T1') {
    const indexHtml = `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>${objective}</title>
  <style>body{font-family:sans-serif;padding:48px;max-width:900px;margin:0 auto}</style>
</head>
<body>
  <h1>${objective}</h1>
  <p>Generated by OpenClaw multi-agent layer.</p>
</body>
</html>`;

    const readme = `# ${objective}

This repo was generated by OpenClaw Orchestrator.

## Tasks
- ${task.id}: ${task.description}
`;

    return {
      task_id: task.id,
      branch,
      commits: [
        {
          message: 'Add landing page scaffold',
          files: [
            { path: 'index.html', content: indexHtml },
            { path: 'README.md', content: readme },
          ],
        },
      ],
      pr: {
        title: `${task.id}: ${task.title}`,
        body: `Automated PR for **${task.id}**.\n\nAcceptance:\n- ${task.acceptance.join('\n- ')}\n`,
      },
    };
  }

  if (task?.id === 'T2') {
    const ci = `name: CI
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate required files
        run: |
          test -f index.html
          test -f README.md
      - name: Basic HTML sanity
        run: |
          grep -qi "<!doctype html" index.html
          grep -qi "<html" index.html
`;

    return {
      task_id: task.id,
      branch,
      commits: [
        {
          message: 'Add CI workflow',
          files: [{ path: '.github/workflows/ci.yml', content: ci }],
        },
      ],
      pr: {
        title: `${task.id}: ${task.title}`,
        body: `Adds CI gate required for auto-merge.\n\nAcceptance:\n- ${task.acceptance.join('\n- ')}\n`,
      },
    };
  }

  return {
    task_id: task?.id,
    branch,
    commits: [],
    pr: {
      title: `${task?.id}: ${task?.title || 'Task'}`,
      body: 'No changes generated.',
    },
  };
}

export function verifierAgent({ task, patch }) {
  const touched = new Set();
  for (const commit of patch?.commits || []) {
    for (const file of commit.files || []) {
      touched.add(file.path);
    }
  }

  const missing = (task?.files_touched || []).filter((filePath) => !touched.has(filePath));
  const ok = missing.length === 0 && (patch?.commits || []).length > 0;

  return {
    task_id: task?.id,
    status: ok ? 'pass' : 'needs_changes',
    notes: ok ? ['Patch matches expected file touches.'] : [`Missing files: ${missing.join(', ')}`],
    required_checks: task?.ci_required ? ['CI/build'] : [],
    test_files: [],
  };
}
